# External libs
import os
import torch
import numpy as np
import itertools
from collections import OrderedDict
import random
import torch
import torch.nn as nn
from torch.autograd import Variable
# Internal libs
from .base_model import BaseModel
from . import networks, loss, util, signal_utils
from . import network_utils as net_utils

class IFPostGANModel(BaseModel):
    """
    """
    def __init__(self, opt, is_train = True):
        """Initialize IF Post processing GAN Model.

        Parameters:
            opt (dict)      - stores all the experiment flags; needs to be a subclass of BaseOptions
            is_train (bool) - Stage flag; {True: Training, False: Testing}
        """
        BaseModel.__init__(self, opt, is_train= True)

        opt['model']['in_ch'] = 1 

        # Instantiating networks
        self.mag2phase = networks.instantiate_mag2phase(opt)
        self.mag2phase.to(self.device)
        self.model_names = ['mag2phase']
        self.load_networks('latest') # Loading only m2p model
        self.model_names = []

        self.postprocessor = networks.instantiate_autoencoder(opt, self.device)
        self.postprocessor.to(self.device)
        self.model_names = ['postprocessor']

        if is_train:  # define discriminators
            self.loss_names = ['g_gan', 'd_gan']

            self.DISC = networks.instantiate_m2p_disc(opt)
            self.DISC.to(self.device)
            self.model_names += ['DISC']

            # specify the training losses you want to print out.
            self.lambda_gan = opt['train']['lambda_gan']
            self.lambda_gp = opt['train'].get('lambda_gan', 0)

            if self.lambda_gp != 0.0:
                self.loss_names.append('gp')

            assert len(self.loss_names) != 0

            # define loss functions
            self.criterion_gan = loss.GANLoss(opt['train']['gan_mode'], self.device)

            # initialize optimizers
            self.optimizer_pp = torch.optim.Adam(self.postprocessor.parameters(), lr=opt['train']['lr'], betas=(opt['train']['beta1'], 0.999))
            self.optimizer_disc = torch.optim.Adam(self.DISC.parameters(), lr=opt['train']['lr'], betas=(opt['train']['beta1'], 0.999))

            if opt['train'].get('load', False):
                self.load_networks(opt['train'].get('load_suffix', 'latest'))
                print('Network Loaded!')
    
    def set_input(self, data):
        # Reference sample for both pitch and timbre
        data = data['data'].to(self.device)
        self.mag = data[:,0:1,:,:]
        self.real_IF = data[:,1:2,:,:]
        data_tmp = torch.transpose(data, 0, 3)
        data_tmp = data_tmp.squeeze(3)
        m2p_IF = self.mag2phase(data_tmp[:,0,:])
        self.m2p_IF = torch.transpose(m2p_IF.unsqueeze(0).unsqueeze(0) \
                    ,2, 3).detach()

    def forward(self):
        """Run forward pass"""
        self.fake_IF, _ = self.postprocessor(self.m2p_IF)
    
    def backward_disc_basic(self, DISC, real, fake):
        """Calculate GAN loss for the discriminator

        Parameters:
            netD (network)      -- the discriminator D
            real (tensor array) -- real images
            fake (tensor array) -- images generated by a generator

        Return the discriminator loss.
        We also call loss_D.backward() to calculate the gradients.
        """

        # Real
        pred_real = DISC(real)
        loss_D_real = self.criterion_gan(pred_real, True)
        loss_D_real.backward()
        
        # Fake
        pred_fake = DISC(fake.detach())
        loss_D_fake = self.criterion_gan(pred_fake, False)
        loss_D_fake.backward()

        # Gradient Penalty
        if self.lambda_gp > 0.0:
            real_data = real.type(torch.FloatTensor).to(self.device).data
            fake_data = fake.type(torch.FloatTensor).to(self.device).data
            loss_gp = loss.cal_gradient_penalty(DISC, real_data, fake_data, self.device, 
                                                lambda_gp= self.lambda_gp)[0]
            loss_gp.backward()
        else:
            loss_gp = 0.0
        # Combined loss and calculate gradients
        loss_D = (loss_D_real + loss_D_fake)*0.5

        return loss_D, loss_gp

    def backward_disc(self):
        """Calculate GAN loss for discriminator D_A"""
        loss_d, loss_gp = self.backward_disc_basic(self.DISC, self.real_IF, self.fake_IF)

        self.loss_d_gan = loss_d 
        self.loss_gp = loss_gp

    def backward_pp(self):
        self.loss_g_gan = self.criterion_gan(self.DISC(self.fake_IF), True)* self.lambda_gan 

        total_loss = self.loss_g_gan
        total_loss.backward(retain_graph=True)

    def optimize_parameters(self):
        """Calculate losses, gradients, and update network weights; called in every training iteration"""
        # forward
        self.forward()

        self.optimizer_pp.zero_grad() 
        self.backward_pp()
        self.optimizer_pp.step()

        self.optimizer_disc.zero_grad() 
        self.backward_disc()
        self.optimizer_disc.step()